apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kibana-ingress
  namespace: logging
spec:
  rules:
  - host: xyz.com
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              number: 5601
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - xyz.com
    secretName: kibana-cert
